from enum import Enum

class rspcode(Enum):
    RSP_OK                           =0,   #[RSP]:OK*/
    RSP_ERROR                        =1,   #[RSP]:Error*/
    RSP_TIMEOUT                      =2,   #[RSP]:Timeout*/
    RSP_UNSUPPORTED                  =3,   #[RSP]:Unsupported*/
    RSP_FIELD_CANT_SAVE              =10,  #[Field]:Cannot save to flash*/
    RSP_FIELD_CNT_TOO_MANY           =11,  #[Field]:Count is too many*/
    RSP_FIELD_READ_ONLY              =12,  #[Field]:Is read only*/
    RSP_FIELD_VAL_TOO_LONG           =13,  #[Field]:Value size too big*/
    RSP_FIELD_INVALID_ID             =14,  #[Field]:Invalid id*/
    RSP_FIELD_INVALID_VAL            =15,  #[Field]:Invalid value*/
    RSP_UOBJ_INVALID_INST_ID         =16,  #[UOBJ]:Invalid instance id*/
    RSP_UOBJ_INVALID_META            =17,  #[UOBJ]:Invalid meta*/
    RSP_UOBJ_INVALID_TYPE_ID         =18,  #[UOBJ]:Invalid type id*/
    RSP_UOBJ_INVALID_MEM_ID          =19,  #[UOBJ]:Invalid member id*/
    RSP_UOBJ_INVALID_MEM_SIZE        =20,  #[UOBJ]:Invalid member size*/
    RSP_UOBJ_HOME_RESET              =21,  #[UOBJ]:HomeLoc reset*/
    RSP_MIS_CANT_MODIFY              =30,  #[MIS]:Modify is forbidden*/
    RSP_MIS_INVALID_ID               =31,  #[MIS]:Id is invalid*/
    RSP_MIS_INVALID_INDEX            =32,  #[MIS]:Index is invalid*/
    RSP_MIS_INVALID_PARA             =33,  #[MIS]:Parameter is invalid*/
    RSP_MIS_INVALID_FILE             =34,  #[MIS]:File is invalid*/
    RSP_MIS_OUT_RANGE                =35,  #[MIS]:Step is out range*/
    RSP_MIS_NO_REL_SERVO             =36,  #[MIS]:Need servo for release*/
    RSP_MIS_NO_CHUTE_SERVO           =37,  #[MIS]:Need servo for chute*/
    RSP_MIS_CO_JOIN_FAIL             =38,  #[MIS]:Join  coroutine fail*/
    RSP_MIS_CO_LEAVE_FAIL            =39,  #[MIS]:Leave coroutine fail*/
    RSP_MIS_NO_RUNWAY                =40,  #[MIS]:No runway found*/
    RSP_MIS_NO_TKF_CMD               =41,  #[MIS]:No takeoff command*/
    RSP_MIS_IS_EMPTY                 =42,  #[MIS]:No flycmd found*/
    RSP_MIS_LOAD_FAIL                =43,  #[MIS]:Load fail*/
    RSP_MIS_DIST_TOO_FAR             =44,  #[MIS]:Distance too far */
    RSP_MIS_NOT_RDY                  =45,  #[MIS]:Not ready*/
    RSP_CTRL_DISALLOW_FLIGHT_STAGE   =70,  #[CTRL]:Disallow in current stage*/
    RSP_CTRL_DISALLOW_IN_AUTO        =71,  #[CTRL]:Disallow in Auto Mode*/
    RSP_CTRL_DISALLOW_IN_FW          =72,  #[CTRL]:Disallow in FW Mode*/
    RSP_CTRL_DISALLOW_IN_MC          =73,  #[CTRL]:Disallow in MC Mode*/
    RSP_CTRL_DISALLOW_IN_RC_AUTO     =74,  #[CTRL]:Disallow in RC Auto Mode*/
    RSP_CTRL_DISALLOW_IN_TKF         =75,  #[CTRL]:Disallow when takeoff*/
    RSP_CTRL_DISALLOW_IN_TRANS       =76,  #[CTRL]:Disallow in Trans Mode*/
    RSP_CTRL_DISALLOW_TRANS_FAIL     =77,  #[CTRL]:Disallow when trans fail*/
    RSP_CTRL_GUIDE_POS_TOO_FAR       =78,  #[CTRL]:Guide target too far*/
    RSP_CTRL_GUIDE_POS_ERR           =79,  #[CTRL]:Invalid guide point*/
    RSP_CTRL_INVALID_FLIGHTMODE      =80,  #[CTRL]:Invalid flight mode*/
    RSP_CTRL_INVALID_PARA            =81,  #[CTRL]:Invalid parameters*/
    RSP_CTRL_INVALID_VTOL_MODE       =82,  #[CTRL]:Invalid VTOL Mode*/
    RSP_CTRL_IS_CRASHED              =83,  #[CTRL]:Is crashed*/
    RSP_CTRL_NEED_AUTO_MODE          =84,  #[CTRL]:Need auto flight mode*/
    RSP_CTRL_NEED_GNSS               =85,  #[CTRL]:Need GNSS*/
    RSP_CTRL_NEED_IDLE_STAGE         =86,  #[CTRL]:Need in idle stage*/
    RSP_CTRL_NEED_LOCKED             =87,  #[CTRL]:Need locked*/
    RSP_CTRL_NEED_OFFGND             =88,  #[CTRL]:Need off ground*/
    RSP_CTRL_NEED_UNLOCKED           =89,  #[CTRL]:Need unlocked*/
    RSP_CTRL_TARGET_POS_ERR          =90,  #[CTRL]:Invalid target point*/
    RSP_CTRL_THR_TOO_LOW             =91,  #[CTRL]:Throttle too low*/
    RSP_CTRL_NEED_FLYING             =92,  #[CTRL]:Need flying state*/
    RSP_CTRL_NEED_GIMBAL             =93,  #[CTRL]:Need gimbal*/
    RSP_CTRL_DISALLOW_IN_LAND        =94,  #[CTRL]:Disallow when landing*/
    RSP_CTRL_AVOID_START             =95,  #[CTRL]:Avoid proc start*/
    RSP_CTRL_AVOID_STOP              =96,  #[CTRL]:Avoid proc stop*/
    RSP_BLOG_DATA_RD_FAIL            =120, #[LOG]:Binlog data read fail*/
    RSP_BLOG_META_RD_FAIL            =121, #[LOG]:Binlog meta read fail*/
    RSP_BLOG_CLR_FAIL                =122, #[LOG]:Binlog data clear fail*/
    RSP_PLOG_DATA_RD_FAIL            =123, #[LOG]:Poslog data read fail*/
    RSP_PLOG_META_RD_FAIL            =124, #[LOG]:Poslog meta read fail*/
    RSP_PLOG_CLR_FAIL                =125, #[LOG]:Poslog data clear fail*/
    RSP_PLOG_NEED_DOWNLOAD           =126, #[LOG]:Poslog data need download*/
    RSP_LOG_INVALID_ID               =127, #[LOG]:Invalid log data id*/
    RSP_LOG_CLR_FAIL_GNSS_FIXED      =128, #[LOG]:Clear fail for GNSS fixed*/
    RSP_LOG_CLR_FAIL_FLASH           =129, #[LOG]:Clear fail for Flash error*/
    RSP_LOG_NO_CARD                  =130, #[LOG]:NO Card*/
    RSP_LOG_NO_FS                    =131, #[LOG]:NO FS*/
    RSP_LOG_CNT_TOO_MUCH             =132, #[LOG]:File count too much*/
    RSP_LOG_WR_ERROR                 =133, #[LOG]:WR Error*/
    RSP_LOG_ALMOST_FULL              =134, #[LOG]:Almost full*/
    RSP_ACC_NOT_RDY                  =150, #[ACC]:Not ready*/
    RSP_ACC_NOT_HEALTHY              =151, #[ACC]:Not healthy*/
    RSP_ACC_NOT_CALIBRATED           =152, #[ACC]:Not calibrated*/
    RSP_GYRO_NOT_RDY                 =153, #[GYRO]:Not ready*/
    RSP_GYRO_NOT_HEALTHY             =154, #[GYRO]:Not healthy*/
    RSP_MAG_NOT_RDY                  =155, #[MAG]:Not ready*/
    RSP_MAG_NOT_HEALTHY              =156, #[MAG]:Not healthy*/
    RSP_MAG_NOT_CALIBRATED           =157, #[MAG]:Not calibrated*/
    RSP_MAG_NOT_CONSISTENT           =158, #[MAG]:Not consistent*/
    RSP_BARO_NOT_RDY                 =159, #[BARO]:Not ready*/
    RSP_BARO_NOT_HEALTHY             =160, #[BARO]:Not healthy*/
    RSP_ASPD_NOT_RDY                 =161, #[ASPD]:Not ready*/
    RSP_ASPD_NOT_HEALTHY             =162, #[ASPD]:Not healthy*/
    RSP_ASPD_NOT_CALIBRATED          =163, #[ASPD]:Not calibrated*/
    RSP_ASPD_NOT_CONSISTENT          =164, #[ASPD]:Not consistent*/
    RSP_GNSS_NOT_RDY                 =165, #[GNSS]:Not ready*/
    RSP_GNSS_GLITCH                  =166, #[GNSS]:Glitch*/
    RSP_GNSS_IS_FAKE                 =167, #[GNSS]:Fake mode*/
    RSP_BAT_IS_LOW                   =168, #[BAT]:Low Voltage*/
    RSP_BAT_IS_FATAL                 =169, #[BAT]:Fatal Voltage*/
    RSP_ACC_NOT_CONSISTENT           =170, #[ACC]:Not consistent*/
    RSP_GNSS_NOT_RTK                 =171, #[GNSS]:Not RTK*/
    RSP_LIC_INVALID_DATA             =200, #[LIC]:Invalid license*/
    RSP_LIC_INVALID_UID              =201, #[LIC]:Invalid Unique ID*/
    RSP_LIC_IGNORE_FOR_FAKEGPS       =202, #[LIC]:Ignore for FakeGPS*/
    RSP_LIC_IGNORE_FOR_SIM           =203, #[LIC]:Ignore for simulation*/
    RSP_LIC_IGNORE_FOR_WHITELISTS    =204, #[LIC]:Ignore for whitelists*/
    RSP_LIC_EXPIRED                  =205, #[LIC]:Expired*/
    RSP_FAILURE_RC                   =210, #[FAIL]:RC*/
    RSP_FAILURE_FENCE                =211, #[FAIL]:FENCE*/
    RSP_FAILURE_GNSS                 =212, #[FAIL]:GNSS*/
    RSP_FAILURE_BAT                  =213, #[FAIL]:BAT*/
    RSP_NOT_SWARM_NDOE               =250, #[SWARM]:Not node*/
    RSP_ATTI_NOT_LEVEL               =301, #[ATTI]:Not level*/
    RSP_INVALID_UAV_TYPE             =302, #[UAV]:Type is invalid*/
    RSP_USB_NOT_CNNT                 =303, #[USB]:Not connected*/
    RSP_INS_NOT_RDY                  =304, #[INS]:Not ready*/
    RSP_AHRS_NOT_RDY                 =305, #[AHRS]:Not ready*/
    RSP_RC_NOT_RDY                   =306, #[RC]:Not ready*/
    RSP_RC_IS_BIAS                   =307, #[RC]:Is bias*/
    RSP_ACT_IS_LOCKED                =308, #[ACT]:Is locked*/
    RSP_ACT_IS_UNLOCKED              =309, #[ACT]:Is unlocked*/
    RSP_CAM_NO_TRIGGER_PIN           =310, #[CAM]:No AUX PIN for shutter*/
    RSP_CAM_INTERVAL_SHORT           =311, #[CAM]:Interval too short*/
    RSP_LNK_INVALID_PARA             =500, #[LNK]:Invalid parameters*/
